# Generated by Django 4.2.1 on 2024-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title', models.CharField(max_length=200, null=True)),
                ('Course_Code', models.CharField(max_length=200, null=True)),
                ('Department', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAS', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Course', models.CharField(max_length=100, null=True)),
                ('Date', models.CharField(max_length=100, null=True)),
                ('Venue', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matric', models.CharField(max_length=200, null=True)),
                ('Course', models.CharField(max_length=200, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100, null=True)),
                ('Matric', models.CharField(max_length=100, null=True)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='Student Profile')),
                ('Department', models.CharField(max_length=100, null=True)),
                ('DOB', models.CharField(max_length=100, null=True)),
                ('Announcement', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
