# Generated by Django 4.2.1 on 2024-05-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSC',
        ),
    ]
